@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 26 20:17:46 +0100 2023
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim coordinate_correction_system_top_behav -key {Behavioral:sim_1:Functional:coordinate_correction_system_top} -tclbatch coordinate_correction_system_top.tcl -view C:/Users/shazz/Downloads/NTNU/MS_in_ESD/Masters Thesis/barrel_distortion_correction/sim result/undistorted_normalized_cordinate_tb_behav.wcfg -view C:/Users/shazz/Downloads/NTNU/MS_in_ESD/Masters Thesis/barrel_distortion_correction/sim result/normalize_cordinates_tb_behav.wcfg -log simulate.log"
call xsim  coordinate_correction_system_top_behav -key {Behavioral:sim_1:Functional:coordinate_correction_system_top} -tclbatch coordinate_correction_system_top.tcl -view C:/Users/shazz/Downloads/NTNU/MS_in_ESD/Masters Thesis/barrel_distortion_correction/sim result/undistorted_normalized_cordinate_tb_behav.wcfg -view C:/Users/shazz/Downloads/NTNU/MS_in_ESD/Masters Thesis/barrel_distortion_correction/sim result/normalize_cordinates_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
